BINARY_PATH=build/yaac
SOURCE_PATH=cmd/yaac/

all: build test

yaac: $(SOURCE_PATH)/*.go
	go build -o ./$(BINARY_PATH)

build:
	go build -o ./$(BINARY_PATH) ./$(SOURCE_PATH)

test:
	go test -v ./test/

run:
	./$(BINARY_PATH)

clean:
	go clean
	rm ./$(BINARY_PATH)

.PHONY: all, build, test, run, clean